In [1]:
#INSTALAR LIBRERIAS
!pip3 install pandas
!pip3 install numpy
!pip3 install matplotlib
!pip3 install seaborn
!pip3 install openpyxl

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.5.2)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/nahomitlapanco/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Citas_Digital.xlsx')
df

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaT,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaT,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaT,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaT,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaT,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   BDC                                       673 non-null      object
 1   Fecha                                     88 non-null       datetime64[us]
 2   Nombre Cliente                            668 non-null      object
 3   Telefono                                  2 non-null        str
 4   Estatus de Lead                           654 non-null      object
 5   Potencial de compra                       614 non-null      object
 6   PDM                                       1048574 non-null  float64
 7   SDC                                       1048573 non-null  float64
 8   Venta                                     1048570 non-null  float64
 9   Asesor Asignado                           656 non-null      str
 10  ¿Por que no ha visitado la agencia?       493 non-null      str
 11  ¿Por que no hay solicitud de credito?     379 non-null      str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null      str
 13  ¿Por que no hubo proceso wow?             364 non-null      str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null      str
 15  Unnamed: 15                               16 non-null       str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 128.0+ MB

In [5]:
#1. Filtro por filas
filtro1= df.iloc[0:673,: ]
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       657 non-null    object
 1   Fecha                                     72 non-null     datetime64[us]
 2   Nombre Cliente                            652 non-null    object
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           638 non-null    object
 5   Potencial de compra                       599 non-null    object
 6   PDM                                       672 non-null    float64
 7   SDC                                       671 non-null    float64
 8   Venta                                     668 non-null    float64
 9   Asesor Asignado                           641 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 84.3+ KB

In [6]:
#2. Filtro por columnas
filtro1= filtro1.iloc[:,[0,1,2,4,5,6,7,8,9]].copy()
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    object
 1   Fecha                72 non-null     datetime64[us]
 2   Nombre Cliente       652 non-null    object
 3   Estatus de Lead      638 non-null    object
 4   Potencial de compra  599 non-null    object
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: datetime64[us](1), float64(3), object(4), str(1)
memory usage: 47.4+ KB

In [7]:
filtro1.shape

(673, 9)

In [8]:
#3. Potencial de compra -> float
filtro1['Potencial de compra'] = filtro1['Potencial de compra'].astype('string')

In [9]:
filtro1['Potencial de compra']=filtro1['Potencial de compra'].str.replace("Ventas ","0", regex=False)

In [10]:
filtro1['Potencial de compra']=filtro1['Potencial de compra'].str.replace("%","", regex=False)

In [11]:
filtro1['Potencial de compra']=filtro1['Potencial de compra'].str.replace("'","", regex=False)

In [12]:
filtro1['Potencial de compra']=filtro1['Potencial de compra'].str.replace("&","", regex=False)

In [13]:

filtro1['Potencial de compra']= filtro1['Potencial de compra'].astype(float)

In [14]:
filtro1['Potencial de compra'].dtype

dtype('float64')

In [15]:
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    object
 1   Fecha                72 non-null     datetime64[us]
 2   Nombre Cliente       652 non-null    object
 3   Estatus de Lead      638 non-null    object
 4   Potencial de compra  599 non-null    float64
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: datetime64[us](1), float64(4), object(3), str(1)
memory usage: 47.4+ KB

In [16]:
filtro1.to_csv("Citas_Digital_General.csv", index=False)

In [17]:
#Filtro por meses
Abril_2025= filtro1.iloc[0:33]

In [18]:
Abril_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  33 non-null     object
 1   Fecha                0 non-null      datetime64[us]
 2   Nombre Cliente       32 non-null     object
 3   Estatus de Lead      32 non-null     object
 4   Potencial de compra  32 non-null     float64
 5   PDM                  32 non-null     float64
 6   SDC                  31 non-null     float64
 7   Venta                31 non-null     float64
 8   Asesor Asignado      31 non-null     str
dtypes: datetime64[us](1), float64(4), object(3), str(1)
memory usage: 2.4+ KB

In [19]:
Abril_2025.to_csv('Abril_2025.csv',index=False)

In [20]:
Mayo_2025= filtro1.iloc[34:59]
Mayo_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
54,Saul,NaT,David,Acrivo,0.90,1.0,1.0,0.0,Aurelio
55,Antonio,NaT,Lia Vera,Venta,0.85,1.0,1.0,1.0,Victor
56,Antonio,NaT,Francisco Mier,Activo,0.70,1.0,0.0,0.0,Victor
57,Antonio,NaT,Ricardo Pedraza Perez,Activo,0.90,1.0,1.0,1.0,Aurelio
58,Antonio/Saul,NaT,Clementina,Venta,0.85,1.0,1.0,1.0,Ricardo

In [21]:
Mayo_2025.to_csv('Mayo_2025.csv',index=False)

In [22]:
Junio_2025 = filtro1.iloc[61:87]
Junio_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
82,Saul,NaT,Jose Miguel,Activo,0.7,1.0,0.0,0.0,Mauricio
83,Antonio,NaT,Olivia rascon sosa,Acitvo,0.6,1.0,1.0,1.0,Mauricio
84,Antonio,NaT,Mireya Eugenia Ceron,Acitvo,0.6,1.0,1.0,1.0,Victor
85,Antonio,NaT,Arturo Alcantar,Acitvo,0.7,1.0,1.0,0.0,Aurelio
86,Saul,NaT,Hugo,Activo,0.6,0.0,0.0,0.0,Alan

In [23]:
Junio_2025.to_csv('Junio_2025.csv',index=False)

In [24]:
Julio_2025 = filtro1.iloc[88:121]
Julio_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
116,Antonio,NaT,Valerio Figueroa,Activo,0.8,1.0,0.0,0.0,Mauricio
117,Antonio,NaT,Sr Martinez,Activo,0.8,1.0,0.0,0.0,Marcos coca
118,Antonio,NaT,German Hernandez,Activo,0.6,1.0,0.0,0.0,Ignacio
119,Saul,NaT,Oscar,Activo,0.8,0.0,1.0,0.0,Daniel
120,Antonio,NaT,Alvaro Vega Tobón,Activo,0.8,1.0,1.0,1.0,Pedro

In [25]:
Julio_2025.to_csv('Julio_2025.csv',index=False)

In [26]:
Agosto_2025 = filtro1.iloc[122:167]
Agosto_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
162,Ana,NaT,Rodrigo.e.jim,Activo,0.5,0.0,0.0,0.0,Ricardo
163,Ana,NaT,"Gabriel Franco , Vazquez",Activo,0.6,0.0,0.0,0.0,Ricardo
164,Antonio,NaT,Marisol Luna Angeles,Activo,0.8,1.0,0.0,0.0,Aurelio
165,Antonio,NaT,"Marcos Benjamin Oviedo, Moreno",Activo,0.6,1.0,0.0,0.0,Victor
166,Ana,NaT,Fernando Pacheco,Activo,0.6,0.0,0.0,0.0,Alan

In [27]:
Agosto_2025.to_csv('Agosto_2025.csv',index=False)

In [28]:
Septiembre_2025 = filtro1.iloc[168:231]
Septiembre_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
226,Ana,NaT,Adriel Zenteno,Activo,0.8,0.0,0.0,0.0,Ana
227,Antonio,NaT,Jose Eduardo Toriz Bustos,Activo,0.8,1.0,0.0,0.0,Alan
228,Ana,NaT,VANNESSA LIZETTE PEREZ CARRANZA,Activo,0.7,0.0,1.0,0.0,Mauricio
229,Ana,NaT,Juan Lopez Cruz,Activo,0.8,0.0,0.0,0.0,Ricardo
230,Antonio,NaT,NADIA LOPEZ GABRIEL,Activo,0.8,0.0,0.0,1.0,Mauricio

In [29]:
Septiembre_2025.to_csv('Septiembre_2025.csv',index=False)

In [30]:
Octubre_2025 = filtro1.iloc[232:291]
Octubre_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
286,Ana,NaT,"Antonio Lopez,",Activo,0.80,0.0,1.0,1.0,Marcos
287,Antonio,NaT,"Todoro Lopez,",Activo,0.70,1.0,1.0,0.0,Pedro
288,Ana,NaT,"Martin Vazquez ,",Activo,0.65,0.0,1.0,0.0,Pedro Antonio
289,Antonio,NaT,"Israel Chavez ,",Activo,0.80,0.0,1.0,0.0,Pedro Antonio
290,Antonio,NaT,Rocio Lopez Mesa,Activo,0.80,1.0,1.0,0.0,Mauricio

In [31]:
Octubre_2025.to_csv('Octubre_2025.csv',index=False)

In [32]:
Noviembre_2025 = filtro1.iloc[292:344]
Noviembre_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
339,Ana,NaT,Cristian Ocampo,Activo,0.7,1.0,1.0,0.0,Ignacio
340,Ana,NaT,"Gloria Elena Benavides,",Activo,0.8,0.0,1.0,0.0,Nancy
341,Antonio,NaT,Efrain Zamudio,Activo,0.8,0.0,1.0,0.0,Aurelio
342,Antonio,NaT,Carolina Ortega,Activo,0.7,0.0,1.0,0.0,Aurelio
343,Antonio,NaT,"Hector Miguel Fernandez ,",Activo,0.8,1.0,1.0,0.0,Pedro

In [33]:
Noviembre_2025.to_csv('Noviembre_2025.csv',index=False)

In [34]:
Diciembre_2025 = filtro1.iloc[345:392]
Diciembre_2025.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
387,Antonio,NaT,Guillermo Canto,Activo,0.7,0.0,0.0,0.0,Ricardo
388,Antonio,NaT,Gabriel Meza,Activo,0.7,0.0,0.0,0.0,Aurelio
389,Antonio,NaT,Jose Miguel,Activo,0.7,0.0,0.0,0.0,Cesar Pestaña
390,Antonio,NaT,Carlos Ignacio,Activo,0.8,0.0,0.0,0.0,Victor
391,Antonio,NaT,Carlos,Activo,0.8,0.0,0.0,0.0,Aurelio

In [35]:
Diciembre_2025.to_csv('Diciembre_2025.csv',index=False)

In [36]:
Enero_2026 = filtro1.iloc[393:429]
Enero_2026.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
424,Antonio,NaT,Julio Cesar,Activo,0.8,0.0,0.0,0.0,Alan
425,Ana,NaT,Luis Aldana,Activo,0.8,1.0,0.0,0.0,Carlos Mejia
426,Ana,NaT,CARLOS ERNESTO PAREDES,Activo,0.8,1.0,0.0,0.0,Julio
427,Ana,NaT,Demetrio Zamara,Activo,0.8,1.0,1.0,0.0,Mauricio
428,Ana,NaT,Roberto De Jesus Lopez,Activo,0.7,0.0,0.0,0.0,Alan

In [37]:
Enero_2026.to_csv('Enero_2026.csv',index=False)

In [38]:
Febrero_2026 = filtro1.iloc[430:461]
Febrero_2026.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
456,Ana,NaT,Israel Hernández Pérez,Activo,0.6,0.0,0.0,0.0,NaN
457,Ana,NaT,JOSE LUIS LOYA,Activo,0.7,1.0,0.0,0.0,Victor
458,Ana,NaT,Brian Michel Villegas,Activo,0.7,1.0,0.0,0.0,Alan
459,Ana,NaT,Hugo Velazquez,Activo,0.7,0.0,0.0,0.0,Mauricio
460,Antonio,NaT,Karen,Activo,0.6,1.0,0.0,0.0,Carlos Hdz

In [39]:
Febrero_2026.to_csv('Febrero_2026.csv',index=False)

In [40]:
Marzo_2026 = filtro1.iloc[462:478]
Marzo_2026.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
473,Ana,NaT,Luis arturo chora lara,Activo,0.7,1.0,0.0,0.0,Julio Cesar
474,Ana,NaT,Jose Isidro,Activo,0.7,1.0,0.0,0.0,Julio Cesar
475,Antonio,NaT,Sergio,Activio,0.8,0.0,0.0,0.0,Mauricio
476,Antonio,NaT,Athalia,Activo,0.9,0.0,0.0,1.0,Cesar Pestaña
477,Antonio,NaT,Alfonso Ramirez,Activo,0.8,1.0,0.0,0.0,Pedro Gonzalez

In [41]:
Marzo_2026.to_csv('Marzo_2026.csv',index=False)

In [42]:
Abril_2026 = filtro1.iloc[479:534]
Abril_2026.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
529,NaN,NaT,Julio Lopez,Activo,0.5,1.0,0.0,0.0,Pedro Gonzalez
530,NaN,NaT,Miguel Antonio Fernandez,Activo,0.7,0.0,0.0,0.0,Nayeli
531,NaN,NaT,Alejandro Sanchez,Activo,0.3,0.0,0.0,0.0,Julio Cesar
532,NaN,NaT,Cesar Palafox,Activo,0.3,0.0,0.0,0.0,Vanny
533,NaN,NaT,HUGO BADILLO,Activo,0.5,0.0,0.0,0.0,Alvaro

In [43]:
Abril_2026.to_csv('Abril_2026.csv',index=False)

In [44]:
Mayo_2026 = filtro1.iloc[540:599]
Mayo_2026.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
594,Ana,NaT,Juan Roque,Activo,1.0,1.0,1.0,0.0,Aurelio
595,Igancio,NaT,Maria guadalupe Serrano,Activo,1.0,0.0,0.0,1.0,Victor
596,Ana,NaT,MARCO ANTONIO CHARTUNI,Activo,0.8,0.0,1.0,0.0,Aurelio
597,Ana,NaT,Alexey,Activo,1.0,1.0,1.0,0.0,Ana
598,Ana,NaT,Brenda Lucero,Activo,1.0,1.0,1.0,0.0,VICTOR

In [45]:
Mayo_2026.to_csv('Mayo_2026.csv',index=False)

In [46]:
Junio_2026 = filtro1.iloc[600:641]
Junio_2026.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
636,Ana,2026-06-24,Paul Kehrli,Activo,0.6,0.0,0.0,0.0,Pedro Antonio
637,Ana,2026-06-15,Benjamin Mendez,Activo,0.7,0.0,0.0,0.0,Vanny
638,Ana,2026-06-06,Reynaldo Cobos,Activo,0.8,1.0,0.0,0.0,Ulises
639,Ana,2026-06-20,Arturo Moreno,Activo,0.5,0.0,0.0,0.0,Nayeli
640,Ana,2026-06-17,Moises Hdez,Activo,0.7,0.0,0.0,0.0,Aurelio

In [47]:
Junio_2026.to_csv('Junio_2026.csv',index=False)

In [48]:
Julio_2026 = filtro1.iloc[642:673]
Julio_2026.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
668,Ignacio,2026-07-21,Carlos Balderrama,Activo,0.5,1.0,1.0,1.0,Mario Varela
669,Ignacio,2026-07-21,Andrés Netzahuatl,Activo,0.5,0.0,0.0,0.0,Mauricio
670,Ana,2026-07-22,Arat Israel,Activo,80.0,1.0,1.0,0.0,Aurelio
671,Ana,2026-07-22,Maira Escalante,Activo,0.8,1.0,1.0,0.0,Pedro Antonio
672,Ignacio,2026-07-22,Zaira Macip,Activo,0.5,0.0,0.0,0.0,Aurelio

In [49]:
Julio_2026.to_csv('Julio_2026.csv',index=False)